export const SUITS=['♠','♥','♦','♣'];export const RANKS=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
export function rand(n){const a=new Uint32Array(1),limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%n}
export function shoe(decks=6){const cards=[];for(let d=0;d<decks;d++)for(const suit of SUITS)for(let r=0;r<13;r++)cards.push({rank:RANKS[r],suit,value:Math.min(r+1,10)});for(let i=cards.length-1;i>0;i--){const j=rand(i+1);[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
export function score(cards){let total=cards.reduce((s,c)=>s+c.value,0),soft=false;if(cards.some(c=>c.value===1)&&total+10<=21){total+=10;soft=true}return{total,soft}}
export class Blackjack{
 constructor(){this.balance=1000000;this.deck=shoe();this.phase='betting';this.hands=[];this.dealer=[];this.active=0;this.returned=0;this.staked=0}
 start(bet){if(this.phase==='playing')throw Error('Finish the current hand');if(!Number.isSafeInteger(bet)||bet<=0||bet>this.balance)throw Error('Insufficient demo balance');if(this.deck.length<52)this.deck=shoe();this.balance-=bet;this.staked=bet;this.returned=0;this.hands=[{cards:[this.deck.pop()],bet,done:false,split:false}];this.dealer=[this.deck.pop()];this.hands[0].cards.push(this.deck.pop());this.dealer.push(this.deck.pop());this.active=0;this.phase='playing';if(score(this.dealer).total===21||score(this.hands[0].cards).total===21)this.settle();return this}
 allowed(){if(this.phase!=='playing')return[];const h=this.hands[this.active],a=['hit','stand'];if(h.cards.length===2&&this.balance>=h.bet){a.push('double');if(this.hands.length===1&&h.cards[0].rank===h.cards[1].rank)a.push('split')}return a}
 action(type){if(!this.allowed().includes(type))throw Error('Action unavailable');const h=this.hands[this.active];if(type==='hit'){h.cards.push(this.deck.pop());if(score(h.cards).total>=21){h.done=true;this.advance()}}if(type==='stand'){h.done=true;this.advance()}if(type==='double'){this.balance-=h.bet;this.staked+=h.bet;h.bet*=2;h.cards.push(this.deck.pop());h.done=true;this.advance()}if(type==='split'){this.balance-=h.bet;this.staked+=h.bet;const second=h.cards.pop();h.split=true;h.cards.push(this.deck.pop());this.hands.push({cards:[second,this.deck.pop()],bet:h.bet,done:false,split:true});if(second.value===1){h.done=true;this.hands[1].done=true;this.advance()}}return this}
 advance(){while(this.active<this.hands.length&&this.hands[this.active].done)this.active++;if(this.active>=this.hands.length){if(this.hands.some(h=>score(h.cards).total<=21))while(score(this.dealer).total<17)this.dealer.push(this.deck.pop());this.settle()}}
 settle(){const d=score(this.dealer).total,dealerNatural=d===21&&this.dealer.length===2;this.returned=0;for(const h of this.hands){const n=score(h.cards).total,natural=n===21&&h.cards.length===2&&!h.split;let payout=0,label='LOSE';if(n>21)label='BUST';else if(dealerNatural){if(natural){payout=h.bet;label='PUSH'}}else if(natural){payout=Math.round(h.bet*2.5);label='BLACKJACK'}else if(d>21||n>d){payout=h.bet*2;label='WIN'}else if(n===d){payout=h.bet;label='PUSH'}h.payout=payout;h.result=label;h.done=true;this.returned+=payout}this.balance+=this.returned;this.phase='settled'}
}
export const baccaratScore=cards=>cards.reduce((s,c)=>s+(c.value===10?0:c.value),0)%10;
export function bankerDraw(total,third){if(third===null)return total<=5;return total<=2||total===3&&third!==8||total===4&&third>=2&&third<=7||total===5&&third>=4&&third<=7||total===6&&third>=6&&third<=7}
export function baccaratRound(deck){const player=[deck.pop()],banker=[deck.pop()];player.push(deck.pop());banker.push(deck.pop());if(baccaratScore(player)<8&&baccaratScore(banker)<8){let third=null;if(baccaratScore(player)<=5){const c=deck.pop();player.push(c);third=c.value===10?0:c.value}if(bankerDraw(baccaratScore(banker),third))banker.push(deck.pop())}const p=baccaratScore(player),b=baccaratScore(banker);return{player,banker,playerScore:p,bankerScore:b,winner:p>b?'player':b>p?'banker':'tie'}}
export function baccaratSettle(bets,result,mult=1){if(![1,2,3,5].includes(mult))throw Error('Invalid multiplier');for(const [key,value]of Object.entries(bets))if(!['player','banker','tie'].includes(key)||!Number.isSafeInteger(value)||value<0)throw Error('Invalid bet');const stake=Object.values(bets).reduce((a,b)=>a+b,0);let payout=0;for(const [key,value]of Object.entries(bets)){if(key===result.winner)payout+=value+Math.round(value*(key==='banker'?.95:key==='tie'?8:1)*mult);else if(result.winner==='tie'&&key!=='tie')payout+=value}return{stake,payout}}
export const megaMultiplier=()=>rand(8)===0?[2,3,5][rand(3)]:1;
