/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BetSlipRouteImport } from './routes/bet-slip'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as CasinoGameIdRouteImport } from './routes/casino.$gameId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as SportsSportIdRouteImport } from './routes/sports.$sportId'
import { Route as SportsSportIdCompetitionSlugRouteImport } from './routes/sports.$sportId.$competitionSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BetSlipRoute = BetSlipRouteImport.update({
  id: '/bet-slip',
  path: '/bet-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoGameIdRoute = CasinoGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => CasinoRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportIdRoute = SportsSportIdRouteImport.update({
  id: '/$sportId',
  path: '/$sportId',
  getParentRoute: () => SportsRoute,
} as any)
const SportsSportIdCompetitionSlugRoute =
  SportsSportIdCompetitionSlugRouteImport.update({
    id: '/$competitionSlug',
    path: '/$competitionSlug',
    getParentRoute: () => SportsSportIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bet-slip': typeof BetSlipRoute
  '/casino': typeof CasinoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sports': typeof SportsRouteWithChildren
  '/casino/$gameId': typeof CasinoGameIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/sports/$sportId': typeof SportsSportIdRouteWithChildren
  '/sports/$sportId/$competitionSlug': typeof SportsSportIdCompetitionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bet-slip': typeof BetSlipRoute
  '/casino': typeof CasinoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sports': typeof SportsRouteWithChildren
  '/casino/$gameId': typeof CasinoGameIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/sports/$sportId': typeof SportsSportIdRouteWithChildren
  '/sports/$sportId/$competitionSlug': typeof SportsSportIdCompetitionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bet-slip': typeof BetSlipRoute
  '/casino': typeof CasinoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sports': typeof SportsRouteWithChildren
  '/casino/$gameId': typeof CasinoGameIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/sports/$sportId': typeof SportsSportIdRouteWithChildren
  '/sports/$sportId/$competitionSlug': typeof SportsSportIdCompetitionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bet-slip'
    | '/casino'
    | '/forgot-password'
    | '/live'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sports'
    | '/casino/$gameId'
    | '/events/$eventId'
    | '/sports/$sportId'
    | '/sports/$sportId/$competitionSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/bet-slip'
    | '/casino'
    | '/forgot-password'
    | '/live'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sports'
    | '/casino/$gameId'
    | '/events/$eventId'
    | '/sports/$sportId'
    | '/sports/$sportId/$competitionSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bet-slip'
    | '/casino'
    | '/forgot-password'
    | '/live'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/sports'
    | '/casino/$gameId'
    | '/events/$eventId'
    | '/sports/$sportId'
    | '/sports/$sportId/$competitionSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BetSlipRoute: typeof BetSlipRoute
  CasinoRoute: typeof CasinoRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SportsRoute: typeof SportsRouteWithChildren
  EventsEventIdRoute: typeof EventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-slip': {
      id: '/bet-slip'
      path: '/bet-slip'
      fullPath: '/bet-slip'
      preLoaderRoute: typeof BetSlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino/$gameId': {
      id: '/casino/$gameId'
      path: '/$gameId'
      fullPath: '/casino/$gameId'
      preLoaderRoute: typeof CasinoGameIdRouteImport
      parentRoute: typeof CasinoRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sportId': {
      id: '/sports/$sportId'
      path: '/$sportId'
      fullPath: '/sports/$sportId'
      preLoaderRoute: typeof SportsSportIdRouteImport
      parentRoute: typeof SportsRoute
    }
    '/sports/$sportId/$competitionSlug': {
      id: '/sports/$sportId/$competitionSlug'
      path: '/$competitionSlug'
      fullPath: '/sports/$sportId/$competitionSlug'
      preLoaderRoute: typeof SportsSportIdCompetitionSlugRouteImport
      parentRoute: typeof SportsSportIdRoute
    }
  }
}

interface CasinoRouteChildren {
  CasinoGameIdRoute: typeof CasinoGameIdRoute
}

const CasinoRouteChildren: CasinoRouteChildren = {
  CasinoGameIdRoute: CasinoGameIdRoute,
}

const CasinoRouteWithChildren =
  CasinoRoute._addFileChildren(CasinoRouteChildren)

interface SportsSportIdRouteChildren {
  SportsSportIdCompetitionSlugRoute: typeof SportsSportIdCompetitionSlugRoute
}

const SportsSportIdRouteChildren: SportsSportIdRouteChildren = {
  SportsSportIdCompetitionSlugRoute: SportsSportIdCompetitionSlugRoute,
}

const SportsSportIdRouteWithChildren = SportsSportIdRoute._addFileChildren(
  SportsSportIdRouteChildren,
)

interface SportsRouteChildren {
  SportsSportIdRoute: typeof SportsSportIdRouteWithChildren
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportIdRoute: SportsSportIdRouteWithChildren,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BetSlipRoute: BetSlipRoute,
  CasinoRoute: CasinoRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SportsRoute: SportsRouteWithChildren,
  EventsEventIdRoute: EventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
